### ISSUE TITLE
Runtime exception - PE.getDataDirectory when toolkit is used with Streams 4.2

### ISSUE THREAD

**Issue by SanjuDabi** [IBMStreams/streamsx.nlp#32]
After upgrading Streams from 3.2 to 4.2, I used the latest toolkit of streamsx.nlp 1.3.0, however it gives below error when initializing JavaOp at runtime.

What is causing this? Is this toolkit compatible with Streams 4.2 ?

The error is same using the latest toolkit com.streamsx.nlp
 
Exception in thread "Thread-11" java.lang.IllegalStateException
        at com.ibm.streams.operator.internal.runtime.api.PE.getDataDirectory(PE.java:211)
        at com.ibm.streamsx.nlp.AbstractUimaOperator.initialize(AbstractUimaOperator.java:506)
        at com.ibm.streamsx.nlp.UimaText.initialize(UimaText.java:127)
        at com.ibm.streams.operator.internal.runtime.api.OperatorAdapter.initialize(OperatorAdapter.java:735)
        at com.ibm.streams.operator.internal.jni.JNIBridge.<init>(JNIBridge.java:271)

**Comment by markheger** [comment]
The toolkit is compatible with Streams 4.2. You need to rebuild the toolkit after changing the Streams Version (make clean all).
Ensure that the data directory exists and write permissions are given for the user. e.g. for Streaming Analytics service (Bluemix) the recommended dataDirectory is /tmp.

**Comment by SanjuDabi** [comment]
What is the variable or parameter to be to set dataDirectory in 4.2?

**Comment by SanjuDabi** [comment]
Specified -C data-directory <path> during submission and it doesn't fail anymore. Just realized default data directory has been removed for 4.0 

https://www.ibm.com/support/knowledgecenter/SSCRJU_4.1.0/com.ibm.streams.install.doc/doc/ibminfospherestreams-migrating-applications-data-dir.html
